### PR TITLE
Some design love

### PR DESCRIPTION
**Pull request by jglovier**
Started spiking out some simple updates to freshen up your steez, yo.

Design mock: 

screenshot 2017-01-02 21 30 12

🚧  **WIP** DO NOT MERGE YET 🚧

### CODE REVIEW

**Comment by tangollama** [comment]
@jglovier, is this branch ready to go?

**Comment by jglovier** [comment]
@tangollama no, not yet. I'll ping you when it's ready for review.

**Comment by jglovier** [comment]
@tangollama k this is ready to go.

**Comment by jglovier** [comment]
@tangollama I just went ahead and merged it. Feel free to make any edits directly to master. :trollface:

**Pull request merged**
